# Generated by Django 4.2.1 on 2023-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospede',
            name='email',
        ),
        migrations.AddField(
            model_name='hospede',
            name='has_fingerprint',
            field=models.BooleanField(default=False, verbose_name='Digital cadastrada'),
        ),
        migrations.AddField(
            model_name='hospede',
            name='phone',
            field=models.CharField(default=28999102019, max_length=150, unique=True, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
