# Generated by Django 4.2.1 on 2023-05-20 21:54

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('relationship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parentesco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('cpf', models.CharField(default='00000000000', max_length=11, unique=True, verbose_name='CPF')),
                ('password', models.CharField(default='123456', max_length=50, verbose_name='Senha')),
                ('first_access', models.BooleanField(default=True, verbose_name='Primeiro acesso')),
                ('chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chat ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('photo', stdimage.models.StdImageField(force_min_size=False, upload_to='photo', variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Foto')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.owner'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data de acesso')),
                ('hour', models.TimeField(auto_now_add=True, verbose_name='Hora de acesso')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guest')),
            ],
        ),
    ]
