# Generated by Django 4.2.1 on 2023-05-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_photo_photo_file_alter_guest_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file',
            new_name='photo',
        ),
    ]
